# Wersja wczytująca plik .env z zewnętrznej lokalizacji
services:
  db:
    image: postgres:15-alpine
    container_name: hs-postgres-db
    restart: unless-stopped
    # <<< POCZĄTEK ZMIAN >>>
    env_file:
      - /DATA/PROJECTS/ENV/.env.scraper
    # <<< KONIEC ZMIAN >>>
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    container_name: hs-scraper-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      db:
        condition: service_healthy
    # <<< POCZĄTEK ZMIAN >>>
    env_file:
      - /DATA/PROJECTS/ENV/.env.scraper
    # <<< KONIEC ZMIAN >>>
    environment:
      # Connection string wciąż jest budowany ze zmiennych wczytanych z pliku .env
      - ConnectionStrings__DefaultConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

volumes:
  postgres_data: